config/routes.rb
Rails.application.routes.draw do
  devise_for :moderator, controllers: {
    sessions: "moderator/sessions"
  }
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }


  resources :mains, only: [:new, :create, :show]
  root 'mains#index'
  get 'mains/users'
  get 'mains/admin'
  get 'mains/moderator'


  resources :posts do
    member do
      patch :approve
    end
    collection do
      get :pending
    end
    resources :comments
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable
  has_many :reports,as: :reportable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :likeable, polymorphic: true
end

app/models/moderator.rb
class Moderator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/models/post.rb
class Post < ApplicationRecord
  enum approval_status: { pending: 'pending', approved: 'approved', denied: 'denied' }

  after_initialize :set_default_approval_status, if: :new_record?

  belongs_to :user
  has_many :suggestions, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :image

  validates :user, presence: true
  validates :title, :content, presence: true

  private

  def set_default_approval_status
    self.approval_status ||= 'pending'
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :reportable, polymorphic: true
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable

  def new
    @comment = @commentable.comments.build
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @commentable, notice: "Comment was successfully created."
    else
      render :new
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    redirect_to @commentable, notice: "Comment was successfully deleted."
  end

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
	before_action :authenticate_user!, only:[:users]
	before_action :authenticate_admin!,only:[:admin]
	before_action :authenticate_moderator,only:[:moderator]
  def index
  	
  end

  def new
  
  end
  def users
  end

  def admin
  end

  def moderator
  end
  def dashboard
  	
  end
def show

end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:users, :create, :new]
  before_action :authenticate_moderator!, only: [:pending, :approve]

  def index
    if user_signed_in?
      @posts = Post.where(approval_status: 'approved').paginate(page: params[:page], per_page: 3)
    elsif moderator_signed_in?
      @posts = Post.all.paginate(page: params[:page], per_page: 3)
    else
      @posts = Post.where(approval_status: 'approved').paginate(page: params[:page], per_page: 3)
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:post][:image_ids]
      params[:post][:image_ids].each do |image_id|
        image = @post.image.find(image_id)
        image.purge
      end
    end
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def users
    @users = User.includes(:posts).all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  def pending
    @posts = Post.where(approval_status: 'pending').paginate(page: params[:page], per_page: 3)
  end

  def approve
    @post = Post.find(params[:id])
    @post.update(approval_status: 'approved')
    redirect_to @post, notice: 'Post approved successfully.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/mains/admin.html.erb
<h1>Mains#admin</h1>
<p>Find me in app/views/mains/admin.html.erb</p>

app/views/mains/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog App</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #1c1c1c;
      color: #f0f0f0;
      font-family: Arial, sans-serif;
    }
    .header {
      background-color: #282828;
      padding: 1em;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      color: #00aaff;
    }
    .content-container {
      margin: 2em auto;
      max-width: 600px;
      text-align: center;
    }
    .links-container {
      margin-top: 2em;
    }
    .links-container a {
      display: inline-block;
      margin: 0.5em;
      padding: 0.5em 1em;
      background-color: #00aaff;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
    }
    .links-container a:hover {
      background-color: #007acc;
    }
    .section-title {
      margin-top: 1em;
      font-size: 1.5em;
      color: #00aaff;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Blog App</h1>
  </div>
  <div class="content-container">
    <% if user_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">User Links</h2>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
        <%= link_to "Edit Registration", edit_user_registration_path %> 
        <%= link_to "All Posts", posts_path %>
      </div>
    <% elsif !admin_signed_in? && !moderator_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">User Links</h2>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
      </div>
    <% end %>
    
    <% if moderator_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">Moderator Links</h2>
        <%= link_to "Sign out", destroy_moderator_session_path, method: :delete, data: { turbo_method: :delete } %>
        <%= link_to "Edit Registration", edit_moderator_registration_path %> 
        <%= link_to "All Posts", posts_path %>
        <%= link_to "Pending Posts", pending_posts_path %>
      </div>
    <% elsif !admin_signed_in? && !user_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">Moderator Links</h2>
        <%= link_to "Sign up", new_moderator_registration_path %>
        <%= link_to "Sign in", new_moderator_session_path %>
      </div>
    <% end %>
    
    <% if admin_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">Admin Links</h2>
        <%= link_to "Sign out", destroy_admin_session_path, method: :delete, data: { turbo_method: :delete } %>
        <%= link_to "Edit Registration", edit_admin_registration_path %>
      </div>
    <% elsif !user_signed_in? && !moderator_signed_in? %>
      <div class="links-container">
        <h2 class="section-title">Admin Links</h2>
        <%= link_to "Sign up", new_admin_registration_path %>
        <%= link_to "Sign in", new_admin_session_path %>
      </div>
    <% end %> 
  </div>
</body>
</html>

app/views/mains/moderator.html.erb
<h1>Mains#moderator</h1>
<p>Find me in app/views/mains/moderator.html.erb</p>

app/views/mains/users.html.erb
<h1>Mains#users</h1>
<p>Find me in app/views/mains/users.html.erb</p>